-kind: ClusterRoleBinding
 -apiVersion: rbac.authorization.k8s.io/v1alpha1
 -metadata:
 -  name: run-storage-e2e
 -subjects:
 -  - kind: ServiceAccount
 -    name: storage-e2e
 -    namespace: armada-storage-e2e-namespace
 -roleRef:
 -  kind: ClusterRole
 -  name: storage-e2e-runner
 -  apiGroup: rbac.authorization.k8s.io
