[Server]
  debug_trace = false

[Bluemix]
  iam_url = "https://iam.bluemix.net"
  iam_client_id = "bx"
  iam_client_secret = "bx"
  iam_api_key = ""
  refresh_token = ""
  containers_api_route = "https://us-south.containers.bluemix.net"

[Softlayer]
  softlayer_block_enabled = false
  softlayer_block_provider_name = "SOFTLAYER-BLOCK"
  softlayer_file_enabled = false
  softlayer_file_provider_name = "SOFTLAYER-FILE"
  softlayer_username = ""
  softlayer_api_key = ""
  softlayer_endpoint_url = "https://api.softlayer.com/rest/v3"
  softlayer_iam_endpoint_url = "https://api.softlayer.com/mobile/v3"
  softlayer_datacenter = "mex01"
  softlayer_api_timeout = "30s"
  softlayer_vol_provision_timeout = "30m"
  softlayer_api_retry_interval = "5s"

[Genesis]
  genesis_provider_enabled = false
  genesis_user_name = ""
  genesis_api_key = ""
  genesis_url = ""

[VPC]
  vpc_enabled = true
  vpc_block_provider_name = "vpc-classic"
  gc_token_exchange_endpoint_url = "https://iam.stage1.bluemix.net"
  gc_riaas_endpoint_url = "https://us-east-stage02.iaasdev.cloud.ibm.com"
  gc_resource_group_id = "XXXX"
  gc_api_key = "XXXX"
  encryption = true
  vpc_timeout = "120s"
  max_retry_attempt  = 5
  max_retry_gap =  30
  api_version = "2019-01-01"

[IKS]
  iks_enabled = true
  iks_block_provider_name = "iks-vpc-classic"
