[server]
  debug_trace = false

[bluemix]
  iam_url = "https://iam.stage1.bluemix.net"
  iam_client_id = "bx"
  iam_client_secret = "bx"
  iam_api_key = ""
  refresh_token = ""
  containers_api_route = "https://containers.test.cloud.ibm.com"
  containers_api_route_private = "https://containers.test.cloud.ibm.com" # "https://private.containers.test.cloud.ibm.com"
  containers_api_csrf_token = ""

[softlayer]
  softlayer_block_enabled = false
  softlayer_block_provider_name = "SOFTLAYER-BLOCK"
  softlayer_file_enabled = false
  softlayer_file_provider_name = "SOFTLAYER-FILE"
  softlayer_username = ""
  softlayer_api_key = ""
  softlayer_endpoint_url = "https://api.softlayer.com/rest/v3"
  softlayer_iam_endpoint_url = "https://api.softlayer.com/mobile/v3"
  softlayer_datacenter = "mex01"
  softlayer_api_timeout = "30s"
  softlayer_vol_provision_timeout = "30m"
  softlayer_api_retry_interval = "5s"

[genesis]
  genesis_provider_enabled = false
  genesis_user_name = ""
  genesis_api_key = ""
  genesis_url = ""

[vpc]
  vpc_enabled = true
  provider_type = "gc"
  vpc_block_provider_name = "vpc-classic"
  gc_token_exchange_endpoint_url = "https://iam.stage1.bluemix.net"
  gc_riaas_endpoint_url = "https://us-south-stage01.iaasdev.cloud.ibm.com"
  gc_riaas_endpoint_private_url = "https://us-south-stage01.iaasdev.cloud.ibm.com" # "https://private-us-south-stage01.iaasdev.cloud.ibm.com"
  gc_resource_group_id = ""
  gc_api_key = ""

  encryption = false
  iks_token_exchange_endpoint_private_url = "https://containers.test.cloud.ibm.com"
  max_retry_attempt  = 10 # 10 times with exponential re-try with max gap max_retry_gap
  max_retry_gap =  120 # 2 minutes
  api_version = "2019-07-02"
  vpc_api_generation = 1
  vpc_api_timeout = "120s"

[IKS]
  iks_enabled = true
  iks_block_provider_name = "iks-vpc-classic"
